---
title: \vspace{2in} 出题系统需求文档
subtitle: "软件质量保障与测试课程Lab1课程作业（第9组）"
author:
  - Tian, Jiahe^[Equal Contribution, Fudan University, 17307130313 (tianjh17@fudan.edu.cn)]
  - Hu, Xiaoxiao^[Equal Contribution, Fudan University, 17302010077 (xxhu17@fudan.edu.cn)]
  - Huang, Jiani^[Equal Contribution, Fudan University, 17302010063 (huangjn17@fudan.edu.cn)]
  - Liu, Jiaxing^[Equal Contribution, Fudan University, 17302010049 (jiaxingliu17@fudan.edu.cn)]
  - Shi, Ruixin^[Equal Contribution, Fudan University, 17302010065 (rxshi17@fudan.edu.cn)]
  - Wu, Chenning^[Equal Contribution, Fudan University, 17302010066 (cnwu17@fudan.edu.cn)]
  - Zhang, Cenyuan^[Equal Contribution, Fudan University, 17302010068 (cenyuanzhang17@fudan.edu.cn)]
  - Zhang, Yihan^[Equal Contribution, Fudan University, 17302010076 (zhangyihan17@fudan.edu.cn)]
  - Wang, Chen^[Equal Contribution, Fudan University, 16307110064 (wangc16@fudan.edu.cn)]

date: "2020年3月12日"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    keep_md: yes
    keep_tex: yes
classoption: "hyperref, a4paper"
nocite: |
  @innovativeInternationalisation, @innovative1, @innovative2, @innovative3, @innovative4, @innovative5, @innovative6, @innovative7, @innovative8, @innovative9, @innovative10, @innovative11, @innovative12, @innovative13, @innovative14, @innovative15, @innovative16
references:
- id: innovativeInternationalisation
  title: "Systems and software engineering — Systems and software Quality Requirements and Evaluation (SQuaRE) — Guide to SQuaRE"
  author:
  - family: International Organization for Standardization
  container-title: International Organization for Standardization
  volume: 2014
  URL: 'https://www.iso.org/standard/64764.html'
  issue: 2
  #publisher: Kluwer Academic Publishers
  #page: 249-275
  type: book
  issued:
    year: 2014
    month: 3

- id: innovative1
  title: "GB/T 25000.51-2016《系统与软件工程系统与软件质量要求和评价 (SQuaRE) 第 51 部分 : 就绪可用软件产品 (RUSP) 的质量要求和测试细则》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 51
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2016
    month: 1
    
- id: innovative2
  title: "GB/T 25000.23-2019《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第23部分：系统与软件产品质量测量》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 23
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2019
    month: 8
    
- id: innovative3
  title: "GB/T 25000.12-2017《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第12部分：数据质量模型》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 12
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2017
    month: 11
    
- id: innovative4
  title: "GB/T 25000.24-2017《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第24部分：数据质量测量》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 24
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2017
    month: 11
    
- id: innovative5
  title: "GB/T 25000.40-201《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第40部分：评价过程》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 40
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2018
    month: 12
    
---

```{r eval=FALSE, include=FALSE}
tinytex::install_tinytex()
```

\newpage

\LARGE

\begin{center}
\textbf{出题系统需求文档}
\end{center}

\large
\begin{center}
\textbf{\emph{软件质量保障与测试课程Lab1课程作业}}
\end{center}

# 摘要 {-}

本次作业为软件质量保障与测试课程的Lab1课程作业，需要我们以小组为单位阅读、理解出题系统初始需求文档，进行小组讨论，结合软件质量相关属性，提出潜在存在的需求重构点，并自定义需求规范撰写需求文档，结合“禅道”平台辅助进行需求管理。

# 关键词 {-}

系统与软件工程; 系统与软件质量要求和评价; 需求文档



# 版本历史 {-}
\begin{center}
%干我的居中失败了why
\begin{tabular}{|l|l|l|}
\hline
版本 & 日期 & 说明\\
\hline
草稿 & 2014 年2 月6 日 & 建立此文档\\
\hline
Alpha 版 & 2014 年2 月8 日 & 做了修改后进行内部评审\\
\hline
Alpha 03 & 2014 年2 月9 日 & 魏X 内部评审稿\\
\hline
Alpha 04 & 2014 年2 月11 日 & 黄X 增加属性，完善评审流程\\
\hline
Alpha 05 & 2014 年2 月14 日 & 增加周X 的问题\\
\hline
Alpha 06 & 2014 年2 月17 日 & 增加T 模块考卷规则、增加分值规则\\
\hline
发布版 1.0 & 2014 年3 月10 日 & 修改后发布\\
\hline
发布版 2.0 & 2014 年3 月16 日 & 评审后，经修改后发布\\
\hline
修订版3.1 & 2014 年4 月25 日 & 与开发商和办公室讨论后收集的建议和问题\\
\hline
修订版3.2 & 2014 年5 月21 日 & 回答魏X 的问题\\
\hline
修订版3.3 & 2014 年6 月30 日 & 根据开发商反馈建议和需求细化后整理。\\
%\hline
%发布版3.0 & 2014 年7 月1 日 & %\makecell[l]{修改后发布。所有状态的描述重新编写，更加便于理解。\\加入新的考题属性“理论实践”。部分修改和完善。}\\
\hline
修订版4.0 & 2020 年3 月12 日 & 进行合理性检查和规范定义后整理。\\
\hline
\end{tabular}
\end{center}

\normalsize

\newpage

\tableofcontents

\newpage
# 在线出题考试系统概述（完整系统）{-}
“在线出题考试系统”是为组织考试的一个基于Web 的在线系统，主要由“出题系统”、“题库管理系统”、“在线报名和考生管理系统”以及“考试系统”四大模块（子系统）组成。

# 出题系统描述 {-}
出题系统是在线出题考试系统的的一个子系统。利用出题系统，出题专家们可以方便的进行网上考题编写和评审，并无缝的与在线出题考试系统进行衔接，提高考题编写的质量和效率，也便于考题的统一管理和评估。
在出题系统中，每一次的出题活动定义为一个“项目”（Project），每个项目有它的目的、内容、角色（成员）、时间（限期）和结果（输出）。例如：某一个项目可能要求出一份或几份完整的，有若干考题组成的完整“考卷”，也有可能是针对某一个或某几个“知识点”编写相应考题。在一个项目中定义了一系列“角色”，如项目的“主持人”、编写考题的“作者”和考题的“评审员”以及最后对考题把关的“质管员”等。
在出题系统中的最小单元是“考题”，“考题”包括了“考题信息”和“考题属性（辅助信息）”，“考题信息”又有“场景描述”（可有可无）、“题干”和“选项”组成；而“辅助信息”是指“考题”在它的整个生命周期中，在管理、统计、评估和自动出考卷过程所使用的一些辅助元素，在这里称为考题的“属性”，包括此考题覆盖大纲的“章节”、“知识点”和“K级（Kn）”、“状态”、“作者”、“评审员”、“质管员”、“发布时间（启用时间）”、“使用次数（使用频率）”、“答对率（每次累加）”、“答错率（每次累加）”、“出题难度（作者的预估）”、“反馈难度（学生反馈）”等（可参看考题属性描述）。这些考题经编写、评审并通过审核后可以“发布”，并以统一的格式导出和存放到题库管理系统。


# 定义（未完成，需完善）
## 基本定义
### 考卷
考卷是由若干考题组成，并按照出题规则，主要根据考卷相对应大纲的知识点（对应大纲的章/节）以及知识点的K级，可参看考卷组成规则。

### 考题
考题是组成考卷的最小单位，由属于考题本身的考题信息以及为管理考题所需的考题属性组成。考题信息又包括该考题场景、考题题干和考题选项。考题属性包含对考题管理所需的各种属性，如考题的作者、考题的ID、考题评审者、考题的状态等，可参看考题属性表。

### 知识点
考题根据大纲所覆盖的章节内容，是出题的依据和范围。且每个知识点有其对应的K级别。

### 正确选项
考题可以是正选题，例如在考题中选择哪项是正确的，也可以是反选题，例如在考题中要求选择哪个是错误或不正确的，无论是正选还是反选题，如果考生做了正确的选择，那个被选中的选项定义为正确的选项。

## 出题系统角色：
### 系统管理员
负责该系统中所有用户账户的开设，创建新项目（项目名+主持人）；对整个系统的配置
和运行负责；维护系统和系统数据（如大纲知识点的更新等）。
### 主持人
整个考题的编写和评审流程的发起人和负责人。指定此次考题对应的大纲知识点，将考
题分配给指定的作者、评审员和质管员，设定考题编写和评审时限。可以导出质管员同
意发布的考题。每题考题的评审员可以有多人。
### 作者
考题的编写者，收到由主持人指定需要出的考题对应的大纲知识点等信息后开始编写考
题，也可根据评审员的意见修改考题。
### 评审员
可对由主持人分配的，并由对应作者已编写的考题进行评审，提出评审和修改意见。
### 质管员
是最后保障考题质量的把关和负责人，由主持人指定考题的质管员，在考题通过评审后
进入“再审”状态，在“再审”状态下质管员决定是否需要返回给作者修改或者直接发
布或者作废。

## 考题的状态
### 开始状态
由主持人创建一个新的考题（考题的ID），新创建考题的状态为“开始”。主持人在开始
状态为考题建立框架，分配考题对应的知识点、时间安排、分配作者和评审员以及质管
员等，完成相关设定后主持人将考题的状态从“开始”改为“编写”状态。
### 编写状态
在“编写”状态下，作者根据被指定的章节知识点来编写考题信息内容（场景，题干，
选项），作者填写必须或应该填写的考题属性内容。作者编写考题完毕后，作者将此考题
的状态从“编写”改写为“评审”状态。
### 评审状态
在“评审”状态下，评审员对作者编写或修改的考题进行评审，每一考题的评审员由主
持人事先指定。评审员完成评审活动后，根据评审结果评审员可将此考题的状态从“评
审”改写为“再审”或“修改”状态。例如，评审结果为“可接受”或“被拒绝”，则评
审员将此考题的状态从“评审”改写为“再审”状态。如果评审结果为“需修改”，则评
审员将此考题的状态从“评审”改写为“修改”状态。
### 再审状态
当考题处于“再审”状态，质管员对考题质量进行再次审核。根据再审结果，质管员可
以将此考题的状态从“再审”改为“修改”、“发布”或“作废”状态。
*备注：评审员或质管员应该在规定时限内完成评审活动并提交评审意见，如果超出规定时限评审员没有完成评审，系统自动向相关评审员或质管员发出提示信息（Mail），并同时向主持人发出信息（Mail），收到信息后主持人根据实际情况重新进行调整，可通过多重渠道进行调整：延长时间、重新安排评审员或质管员、直至删除该题等。*
### 修改状态
当考题处于“修改”状态时，考题的作者可以对考题进行修改，作者一般是参照评审的
记录和要求对考题进行修改。修改完毕后，作者可将此题的状态从“修改”改为“评审”
状态。
### 发布状态
当考题处于“发布”状态时，表示此题已经通过编写和评审，可以被使用了。主持人可
以导出此状态下的考题。主持人可以单题导出，也可以批量导出。
### 作废状态
当考题处于“作废”状态时，表示此题由于各种原因不被接受，也不会使用，主持人对
此类考题按照规定进行处理，例如删除。

# 功能性需求

## 登陆及个人信息

### 功能-需求名
- 关键词
- 需求描述（参考模板：作为一种<某类型的用户>,我希望<达成某些目的>,这样可以<开发的价值>)
- 验收标准
- （图）

### 功能-需求名2
- 关键词
- 需求描述（参考模板：作为一种<某类型的用户>,我希望<达成某些目的>,这样可以<开发的价值>)
- 验收标准
- （图）

## 建立新项目

### 功能-需求名3
- 关键词
- 需求描述（参考模板：作为一种<某类型的用户>,我希望<达成某些目的>,这样可以<开发的价值>)
- 验收标准
- （图）

## 开始启动项目(状态: 开始; 角色: 主持人)

## 编写考题(状态: 编写; 角色: 作者)

## 评审考题(状态: 评审; 角色: 评审员)

## 再审考题(状态: 再审; 角色: 质管员)

## 修改考题(状态: 修改; 角色: 作者)

## 发布考题(状态: 发布; 角色: 主持人)

## 作废考题(状态: 作废; 角色: 主持人)

# 质量需求
## 质量-性能需求
- 关键词：响应速度
- 需求描述：系统响应速度足够快，以避免打断用户的思路。
- 验收标准：在95%的情况下，响应时间将不超过1.5秒，在其他情况下不超过4秒。

## 质量-性能需求
- 关键词：并发性
- 需求描述：出题系统要有协同工作的能力，能同时并行工作。
- 验收标准：支持动态用户（在线用户）在1500以上，支持静态用户（注册用户）在50000以上，支持并发数（同时工作用户）300以上。

## 质量-可移植性
- 关键词：浏览器兼容
- 需求描述：出题系统基于Web 浏览器，可以在常见的和通用的浏览器的当前版本下正常工作。
- 验收标准：出题系统应在Internet Explorer，Firefox，google chrome, Opera最新版本下正常工作。

## 质量-可移植性
- 关键词：平台
- 需求描述：出题系统是不依赖与某种特定平台的系统。
- 验收标准：出题系统应可以正常运行在Windows 系统、Mac OS 或Linux 平台。

## 质量-可移植性
- 关键词：数据库
- 需求描述：出题系统的数据库有很好的更新能力，能够适应迭代开发。
- 验收标准：至少支持免费的数据库系统（MySQL），替换关系数据库系统的平均时间不超过2小时，并且保证没有数据丢失。

## 质量-安全性需求
- 关键词：保密性 权限控制
- 需求描述：严格权限访问控制，用户在经过身份认证后，只能访问其权限范围内的数据，只能进行其权限范围内的操作。
- 验收标准：在1000次数据的修改全部由对应权限的人员完成，没有例外。

## 质量-安全性需求
- 关键词：断电 掉线 故障处理
- 需求描述：在断电、掉线情况下不会丢失数据。
- 验收标准：在1000次断电、掉线测试中数据保存完好，没有例外。

## 质量-安全性需求
- 关键词：数据安全
- 需求描述：系统必须保障数据安全。
- 验收标准：对一些重要的数据利用可靠的加密技术进行加密，例如用户的密码等。网络传递数据也应经过加密。需要保证数据在采集、传输和处理过程中不被偷窥、窃取、篡改。考题数据需要在存储时进行加密，确保不可破解。

## 质量-安全性需求
- 关键词：攻击
- 需求描述：必须保障系统的安全和可靠，具有防黑客能力，能经受来自互联网的一般性恶意攻击。
- 验收标准：能防止一般的病毒（包括木马）攻击、口令猜测攻击、黑客入侵等。至少99%的攻击需要在10秒内检测到。

## 质量-可靠性
- 关键词：数据备份
- 需求描述：系统应保障出现故障后数据依旧完整。
- 验收标准：系统提供数据备份和恢复功能，使得在由于系统的错误或其他原因引起系统的数据丢失或系统的数据被破坏时，其中99%的情况能够及时恢复和还原数据。

## 质量-可靠性
- 关键词:容错性 健壮性
- 需求描述：系统具有一定的容错和抗干扰能力,能处理系统运行过程中出现的各种异常情况，如：人为操作错误、输入非法数据、硬件设备失败等。
- 验收标准：在非硬件故障或非通讯故障时，系统能够保证正常运行，并有足够的提示信息帮助用户有效正确地完成任务。在10,000次错误测试中,因软件系统的失效而造成不能完成业务的概率小于5‰，最多出现1次需要重新启动系统的情况。

## 质量-易用性
- 关键词:易学习性 易理解性
- 需求描述：支持没有计算机使用经验、计算机使用经验较少及有较多计算机使用经验的用户方便地使用本系统。
- 验收标准：界面简洁美观，操作简单,80%的用户在接受一个2小时的系统介绍培训后，可以熟练使用该系统。

## 质量-易用性
- 关键词：易操作性
- 需求描述：系统进行操作时有统一规范的提示信息。
- 验收标准：对必填项进行有效统一的提示；删除操作时，系统提示警示框，用户点击确认后，系统才执行删除操作，删除后可直接返回相关页面。

## 质量-可维护性
- 关键词：易分析性
- 需求描述：系统代码应便于开发人员维护。
- 验收标准：提供运行日志管理及安全审计功能，可追踪系统的历史使用情况,日志记录系统运行所发生的所有错误，包括本机错误和网络错误。。保留系统对应的版本的源代码。代码有注释并且描述清晰。系统具有清晰的系统结构和命名规范，界面规范，提示和帮助信息规范，友好的错误提示信息，可以帮助用户自己找原因，自己维护系统。90%的BUG修改时间不超过1个工作日，其他不超过2个工作日。

# 约束条件
## 约束-政策需求
- 关键词：国家安全标准
- 需求描述:系统安全性符合中华人民共和国国家标准GB/T 22239-2008。
- 验收标准:《信息系统安全等级保护基本要求》中每一项出题系统都符合。



\pagebreak

# 参考文献 {-}