---
title: \vspace{2in} 出题系统需求文档
subtitle: "软件质量保障与测试课程Lab3课程作业（第9组）"
author:
  - Tian, Jiahe^[Equal Contribution, Fudan University, 17307130313 (tianjh17@fudan.edu.cn)]
  - Hu, Xiaoxiao^[Equal Contribution, Fudan University, 17302010077 (xxhu17@fudan.edu.cn)]
  - Huang, Jiani^[Equal Contribution, Fudan University, 17302010063 (huangjn17@fudan.edu.cn)]
  - Liu, Jiaxing^[Equal Contribution, Fudan University, 17302010049 (jiaxingliu17@fudan.edu.cn)]
  - Shi, Ruixin^[Equal Contribution, Fudan University, 17302010065 (rxshi17@fudan.edu.cn)]
  - Wu, Chenning^[Equal Contribution, Fudan University, 17302010066 (cnwu17@fudan.edu.cn)]
  - Zhang, Cenyuan^[Equal Contribution, Fudan University, 17302010068 (cenyuanzhang17@fudan.edu.cn)]
  - Zhang, Yihan^[Equal Contribution, Fudan University, 17302010076 (zhangyihan17@fudan.edu.cn)]
  - Wang, Chen^[Equal Contribution, Fudan University, 16307110064 (wangc16@fudan.edu.cn)]

date: "2020年4月1日"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    keep_md: yes
    keep_tex: yes
classoption: "hyperref, a4paper"
nocite: |
  @innovativeInternationalisation, @innovative1, @innovative2, @innovative3, @innovative4, @innovative5, @innovative6, @innovative7, @innovative8, @innovative9, @innovative10, @innovative11, @innovative12, @innovative13, @innovative14, @innovative15, @innovative16
references:
- id: innovativeInternationalisation
  title: "Systems and software engineering — Systems and software Quality Requirements and Evaluation (SQuaRE) — Guide to SQuaRE"
  author:
  - family: International Organization for Standardization
  container-title: International Organization for Standardization
  volume: 2014
  URL: 'https://www.iso.org/standard/64764.html'
  issue: 2
  #publisher: Kluwer Academic Publishers
  #page: 249-275
  type: book
  issued:
    year: 2014
    month: 3

- id: innovative1
  title: "GB/T 25000.51-2016《系统与软件工程系统与软件质量要求和评价 (SQuaRE) 第 51 部分 : 就绪可用软件产品 (RUSP) 的质量要求和测试细则》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 51
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2016
    month: 1
    
- id: innovative2
  title: "GB/T 25000.23-2019《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第23部分：系统与软件产品质量测量》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 23
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2019
    month: 8
    
- id: innovative3
  title: "GB/T 25000.12-2017《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第12部分：数据质量模型》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 12
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2017
    month: 11
    
- id: innovative4
  title: "GB/T 25000.24-2017《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第24部分：数据质量测量》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 24
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2017
    month: 11
    
- id: innovative5
  title: "GB/T 25000.40-201《系统与软件工程 系统与软件质量要求和评价(SQuaRE) 第40部分：评价过程》"
  author:
  - family: 中国国家标准化管理委员会
  container-title: 系统与软件工程系统与软件质量要求和评价 (SQuaRE)
  volume: 40
  URL: 'http://openstd.samr.gov.cn'
  publisher: 中国国家标准化管理委员会
  type: book
  issued:
    year: 2018
    month: 12
    
---

```{r eval=FALSE, include=FALSE}
tinytex::install_tinytex()
```

\newpage

\LARGE

\begin{center}
\textbf{出题系统测试文档}
\end{center}

\large
\begin{center}
\textbf{\emph{软件质量保障与测试课程Lab3课程作业}}
\end{center}

# 摘要 {-}

本次作业为软件质量保障与测试课程的Lab3课程作业，需要我们以小组为单位撰写在线出题考试系统的IEEE829测试文档.

# 关键词 {-}

系统与软件工程; 系统与软件质量要求和评价; 测试文档

\normalsize

\newpage

\tableofcontents

\newpage

# 目的
本测试计划的⽬的为按照详细的计划测试在线出题考试系统的四个子系统：出题系统、题库管理系统、考试系统、在线报名考生系统及其之间接⼝的测试。最终⽬的是保证在线出题考试系统的正常运⾏。

# 测试计划标识
CSTM1.0-TP1.0
修订历史
\begin{tabular}{|p{2cm}|p{3.3cm}|p{5cm}|}
\hline
版本 & 日期 & 说明\\
\hline
草稿 & 2021 年3 月7 日 & 基于出题系统的测试计划草稿\\
\hline
CSTM1.0-TP1.0 & 2021 年4 月1 日 & 建立更完善的出题系统的测试计划\\
\hline
\end{tabular}

# 介绍
## 目标
本测试计划基于Lab2版本的CS出题系统，本测试文档将涵盖以下方面：
1. 定义测试过程所需的测试方法与工具
2. 与相关人员沟通测试任务分派，确定测试时间表、测试环境与风险控制
3. 定义测试进行的具体步骤

## 测试软件情况介绍：
- 出题系统：出题系统是在线出题考试系统的的⼀个⼦系统。利⽤出题系统，出题专家们可以⽅便的进⾏⽹上考题编写和评审，并⽆缝的与在线出题考试系统进⾏衔接，提⾼考题编写的质量和效率，也便于考题的统⼀管理和评估。
- 题库管理系统：题库管理系统是在线出题考试系统的的⼀个⼦系统。他的输⼊是出题系统成功导出的考题，可以为考试系统按照规则导出考卷。
- 考试系统：考试系统是在线出题考试系统的的⼀个⼦系统。用户完成作答之后，考题系统可以自动批改试卷并给出相应得分。
-  在线报名考试管理系统：在线报名考试管理系统是在线出题考试系统的的⼀个⼦系统。考生能够根据既定的考生信息登陆考试系统，查看属于自己相对应的考卷，然后在规定的时间内作答。在作答后可以查看考试成绩。

# 测试项
## 出题系统
### 登陆及个人信息
#### 用户登录校验
1. 先决条件：用户已经成功在系统中注册过自己的用户名和密码
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项：
    + 用户输入正确用户名和密码可以成功登录，登录状态由“未登录”变为对应用户名。
    + 用户输入错误用户名和密码无法登陆系统，提示“用户名或密码”错误，允许继续输入，不允许对考题进行任一操作。

#### 用户修改个人信息
1. 先决条件：用户登陆系统成功
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项：
    - 用户可以对用户信息（包括用户名、密码、其他信息等）进行修改，修改完成后自动更新用户信息。

### 建立新项目
#### 主持人创建项目
1. 先决条件：登陆用户角色为主持人
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项：
    - 主持人可以创建新的出题系统，一旦创建不允许更换其他主持人。
    - 主持人在创建时定义项目名，不能与其他出题系统重复，不允许创建完成后再修改项目名。
    - 主持人在创建项目时可以成功对项目进行规划，如限制项目考题数量或考题范围。
    - 系统在主持人成功创建项目并完成项目设置后自动发送邮件提示主持人。

#### 主持人新建考题
1. 先决条件：登陆用户角色为主持人且完成项目创建
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项：
    - 主持人可以创建新考题，成功创建的考题有唯一不重复ID。
    - 主持人可以设置新考题状态为“开始”。
    - 主持人在开始状态下可以为考题设置题目属性（如知识点，时间点、时间安排）
    - 主持人在开始状态下可以为考题设置相关管理人员，包括作者、评审员、质管员。其中不同身份不能安排同一名用户，如作者与评审员不能有同一个用户ID。每个身份要求至少安排一人，允许为一道考题安排多名作者、评审员、质管员。
    - 考题相关的评审员和作者之间可以互相读取权限信息。
    - 系统在主持人成功新建题目、设置题目属性与作者、评审员、质管员后会自动发送邮件给对应管理人员进行确认。

### 开始启动项目
#### 主持人设置考题期限
1. 先决条件：登陆用户角色为主持人且已设置考题状态为“开始”
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 主持人能够为状态为“开始”的考题设定编写考题与评审考题的时间限期。
    - 系统会对超出限期的任务报警，自动发送邮件或站内信给主持人。
    - 主持人能对超出限期的任务提出警告或延长时间限期。

#### 主持人修改状态(开始-编写)
1. 先决条件：登陆用户角色为主持人且已设置考题状态为“开始”
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项：
    - 主持人在开始状态下完成了对题目属性的设置、知识点的分配、作者、评审员和质管员的设置后，可以将题目状态改为“编写”。
    - 系统在题目状态改变为“编写”后能自动给对应作者发送提示邮件。
    - 主持人未完成相关设置的题目不能修改状态。
    - 主持人能够批量将完成分配的题目状态改为“编写”，系统会给对应作者发送邮件
    - 在考题状态为“开始”下，除主持人外，系统管理员、作者、评审员没有修改题目状态的权限。

### 编写考题
#### 作者设置多类型考题
1. 先决条件：登陆用户角色为作者并已被主持人分配出题任务
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 作者能够看到由主持人分配给自己编写的考题的相关信息。
    - 作者能够编写普通（纯文字）考题并设置相关属性。
    - 作者能够编写带有表格的题目并正确显示，无乱码并设置相关属性。
    - 作者能够编写带有图形的题目并正确显示，无乱码并设置相关属性。
    - 作者需要对题目给出标准答案并设置相关属性（如题型、知识点、分值等）。
    - 普通考题能以XML，Excel的形式导入出题系统
    - 带有表格的题目能以XML，Excel的形式导入出题系统
    - 带有图形的题目能以XML，Excel的形式导入出题系统

#### 作者修改状态(编写-评审)
1. 先决条件：登陆用户角色为作者并已被主持人分配出题任务
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 作者不可以对评审员、质管员进行修改，也不可以修改题目的编写时间限制或所属项目。仅允许且必须对题干、答案和部分题目属性进行编写和设置。
    - 对未完成编写（如题干为空等情况），未给出标准答案或未完成相关属性设定的题目，作者不能修改其状态为“评审”。
    - 作者能够将编写完成、给出标准答案并设置相关属性的题目状态改为“评审”。
    - 系统在题目状态改为“评审”后给评审员发出邮件。
    - 主持人在编写过程中没有修改和操作的权限。
    
#### 作者设置多类型考题2
1. 先决条件：登陆用户角色为作者并已被主持人分配出题任务
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
    - 在编写状态下，作者可以使用 latex语法在文本中插入数学公式/符号，要求数学公式可以正确显示、存储，无乱码。也可以将带有latex语法的数学公式题目以Excel, Xml 导入题库。

#### 送审前内容检查
1. 先决条件：作者准备将考题从编写变为评审
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
    - 如果题干中出现“如图”“表格”关键字，检查是否添加了图片和表格，如果没有则给出提醒并拒绝状改变。

### 评审考题
#### 评审员设置评审结果为“可接受”
1. 先决条件：登陆用户角色为评审员并有需要此用户评审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 评审员能够设置评审结果为“可接受”，考题的状态从“评审”变为“再审”。
    - 系统在状态变化后通过邮件提醒相关质管员并提示评审信息。

#### 评审员设置评审结果为“被拒绝”
1. 先决条件：登陆用户角色为评审员并有需要此用户评审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 评审员能够设置评审结果为“被拒绝”，考题的状态从“评审”修改为“再审”。
    - 系统在状态变化后通过邮件提醒相关质管员并提示评审信息。

#### 评审员设置评审结果为“需修改”
1. 先决条件：登陆用户角色为评审员并有需要此用户评审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 评审员能够设置评审结果为“需修改”，考题的状态从“评审”变为“修改”。
    - 系统在状态变化后通过包含评审信息的邮件提醒相关作者修改。

#### 评审员评审权限
1. 先决条件：登陆用户角色为评审员，考题处于“评审”状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 评审员有权阅读被主持人分配属于自己评审的考题
    - 评审员有权对被主持人分配属于自己评审的考题编写评审意见和建议（包括指出考题的错误）
    - 评审员无权改变被主持人分配属于自己评审的考题（包括内容，属性及其他）
    - 评审员有权改变被主持人分配属于自己评审的考题的状态
    - 评审员无权阅读其他考题
    - 评审员无权对其他考题编写评审意见和建议（包括指出考题的错误）
    - 评审员无权改变其他考题（包括内容，属性及其他）
    - 评审员无权改变其他考题的状态
    - 主持人否有权阅读考题
    - 主持人无权对考题编写评审意见和建议（包括指出考题的错误）
    - 主持人无权改变考题（包括内容，属性及其他）
    - 主持人无权改变考题的状态
    - 其他角色无权阅读考题
    - 其他角色无权对考题编写评审意见和建议（包括指出考题的错误）
    - 其他角色无权改变考题（包括内容，属性及其他）
    - 其他角色无权改变考题的状态

### 再审考题
#### 质管员设置再审结果为“可发布”
1. 先决条件：登陆用户角色为质管员并有需要此用户再审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 质管员能够设置再审结果为“可发布”，考题的状态从“再审”变为“发布”。
    - 系统在状态改变后能够通过邮件提醒主持人。

#### 质管员设置再审结果为“需修改”
1. 先决条件：登陆用户角色为质管员并有需要此用户再审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 质管员能够设置再审结果为“需修改”，考题的状态从“再审”变为“修改”。
    - 系统在状态改变后能够通过邮件提醒作者。

#### 质管员设置再审结果为“需作废”
1. 先决条件：登陆用户角色为质管员并有需要此用户再审的考题
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 质管员能够设置再审结果为“需作废”，考题的状态从“再审”变为“作废”。
    - 系统在状态改变后能够通过邮件提醒主持人。

#### 质管员再审权限
1. 先决条件：登陆用户角色为质管员，考题处于“再审”状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 质管员有权阅读考题
    - 质管员有权对考题编写评审意见和建议（包括指出考题的错误）
    - 质管员无权改变考题（包括内容，属性及其他）
    - 主持人有权阅读考题
    - 主持人无权对考题编写评审意见和建议（包括指出考题的错误）
    - 主持人无权改变考题（包括内容，属性及其他）
    - 主持人无权改变考题的状态
    - 其余角色无权阅读考题
    - 其余角色无权对考题编写评审意见和建议（包括指出考题的错误）
    - 其余角色无权改变考题（包括内容，属性及其他）
    - 其余角色无权改变考题的状态

### 修改考题
#### 作者修改考题
1 先决条件：登陆用户角色为作者，考题处于修改状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 作者能够阅读修改要求及意见。
    - 作者将题目状态设置为“评审”后，系统自动给评审员发送状态变化的邮件提醒。

#### 作者修改权限
1. 先决条件：考题处于“修改”状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 作者能够阅读所有需要自己修改的考题
    - 作者可以对需要自己修改的考题（包括内容及属性）进行改动
    - 作者无权对评审员，质管员，编写时间限制，所属项目等进行修改
    - 作者可以改变处于“修改”且需要自己修改的考题的状态从“修改”到“评审”而非其他状态
    - 主持人能够阅读考题
    - 主持人无权对这些考题（包括内容，属性及其他）进行改动
    - 主持人无权改变考题的状态从“修改”到其他状态
    - 作者不能够阅读不需要自己修改的考题
    - 作者无权对不需要自己修改的考题（包括内容，属性及其他）进行改动
    - 作者无权改变处于“修改”状态且不需要自己修改的考题的状态从“修改”到“评审”
    - 作者无权改变处于“修改”状态且不需要自己修改的考题的状态从“修改”到其他状态
    - 其余角色不能够阅读考题
    - 其余角色无权对这些考题（包括内容，属性及其他）进行改动
    - 其余角色无权改变考题的状态从“修改”到其他状态
    
#### 修改次数超过提醒
1. 先决条件：考题进入修改状态超过3次
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
    - 如果考题进入修改状态超过3次，系统会给主持人发送邮件提示。

### 发布考题
#### 主持人导出发布考题
1. 先决条件：考题处于“发布”状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 主持人可以阅读这些考题
    - 主持人可以根据考题导出规则导出考题
    - 主持人不可以修改考题（包括内容，属性及其他）
    - 主持人不可以修改考题的状态
    - 导出的考题需要符合考题导出规则
    - 导出的考题包括考题最终发布版本的所有完整内容及属性，或者同时导出考题的历史数据
    - 导出的考题文件可以为Excel或XML格式
    - 导出的考题中不含有冗余信息
    - 其余角色不可以阅读这些考题
    - 其余角色不可以导出考题
    - 其余角色不可以修改考题（包括内容，属性及其他）
    - 其余角色不可以修改考题的状态

#### 主持人导入题库
1. 先决条件：考题已发布，并由主持人以XML或Excel形式导出
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 题库系统管理员可以将符合以上先决条件的XML文件导入题库
    - 题库系统管理员可以将符合以上先决条件的Excel文件导入题库
    - 题库系统管理员不可以将未发布的考题导入题库
    - 题库系统管理员不可以将未经主持人导出的考题导入题库
    - 题库系统管理员不可以将非合法考题形式的XML或Excel文件导入题库
    - 其他角色不可以将任意XML或Excel文件导入题库

### 作废考题
#### 主持人废除作废考题
1. 先决条件：考题处于作废状态
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 主持可以废除考题
    - 废除后的考题不能被使用（包括阅读及修改）
    - 主持人不能修改考题（包括内容，属性及其他）
    - 主持人不能修改考题的状态
    - 其余角色不能查看考题
    - 其余角色没有废除考题的权限
    - 其余角色不能修改考题（包括内容，属性及其他）
    - 其余角色不能修改考题的状态

#### 主持人重启出题流程
1. 先决条件：主持人对于处于作废状态的考题进行判断后，发现无法达成出题目的和要求
2. 代码版本：CS_TESTMAKER_1.0
3. 测试项:
    - 主持人拥有重启项目的权限
    - 主持人重启项目后，旧项目中的考题不能被阅读和修改
    - 主持人重启项目后，新项目中的考题能够正常编写及被评审

## 题库管理系统
### 考题处理
#### 有权限用户查阅考题
1. 先决条件：登陆用户为主持人或具有查看权限的用户
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项：
    - 可以按照考题属性搜索查阅相关考题
    
#### 生成考卷
1. 先决条件：登陆用户为主持人或具有查看权限的用户
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项：
    - 系统可以根据考卷组成规则（见出题系统需求文档发布版3.0附录2）自动从题库中抽取已经出好的题生成考卷
    - 系统在题库内题目不足以构成考卷时提示，并终止生成考卷
    - 生成考卷同时可以同时生成正确的答案
    
## 考试系统
### 批改
#### 批改考题
1. 先决条件：已有用户作答的考卷数据与正确答案
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项：
  - 考试系统可以自动批改试卷并给出相应得分。

## 在线报名考生管理系统 
### 登陆及查看
#### 用户登录校验
1. 先决条件：用户已经成功在系统中注册过自己的用户名和密码
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项：
    + 用户输入正确用户名和密码可以成功登录，登录状态由“未登录”变为对应用户名。
    + 用户输入错误用户名和密码无法登陆系统，提示“用户名或密码”错误，允许继续输入。
    
#### 查看考卷与作答 
1. 先决条件：用户已经成功在系统中登陆
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项：
  - 用户可以查看自己将要作答的考卷并在规定时间内作答
  - 用户在作答后可以看见自己的考试成绩

## 系统质量
### 响应速度
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 在95%的情况下，响应时间将不超过1.5秒，在其他情况下不超过4秒。

### 并发要求
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 支持动态用户（在线用户）在1500以上，支持静态用户（注册用户）在50000以上，支持并发数（同时工作用户）300以上。

### 浏览器可移植性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 出题系统应在Internet Explorer，Firefox，google chrome, Opera最新版本下正常工作。

### 平台可移植性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 出题系统应可以正常运行在Windows 系统、Mac OS 或Linux 平台。

### 数据库可移植性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 出题系统的数据库有很好的更新能力，能够适应迭代开发。至少支持免费的数据库系统（MySQL），替换关系数据库系统的平均时间不超过2小时，并且保证没有数据丢失。便于之后出现系统升级更换数据库系统的情况。

### 用户安全性需求
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 严格权限访问控制，用户在经过身份认证后，只能访问其权限范围内的数据，只能进行其权限范围内的操作。在1000次数据的修改全部由对应权限的人员完成，没有例外。

### 系统一致性需求
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 在1000次断电、掉线测试中数据保存完好，没有例外。

### 数据安全性需求
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统可以保障数据的安全
    + 对一些重要的数据在存储时利用可靠的加密技术进行加密，例如用户的密码等。
    + 网络传递数据时也应经过加密，需要保证数据在采集、传输和处理过程中不被偷窥、窃取、篡改。
    + 考题数据需要在存储时进行加密，确保不可破解。

### 系统安全性需求
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统安全可靠，具有防黑客能力，能经受来自互联网的一般性恶意攻击
    + 可以防止一般的病毒（包括木马）攻击、口令猜测攻击、黑客入侵等
    + 至少90%的攻击需要在10秒内检测到。

### 数据可靠性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统做到了数据备份
    + 在由于系统的错误或其他原因引起系统的数据丢失或系统的数据被破坏时，能够及时恢复和还原数据。

### 系统可靠性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统是健壮的
    + 在非硬件故障或非通讯故障时，系统能够保证正常运行100小时以上
    + 在10,000次错误测试中,因软件系统的失效而造成不能完成业务的概率小于5‰，最多出现1次需要重新启动系统的情况。

### 用户易用性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统应该便于用户上手，80%的没有计算机领域经验的用户在接受一个2小时的系统介绍培训后，可以熟练使用该系统
- 界面简洁美观，操作简单

### 系统易用性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统进行操作时有统一规范的提示信息
    + 每个操作成功时都有对应的提示
    + 每个操作失败时都有对应的提示
        - 操作失败时的提示指明操作失败的原因
    + 系统出错时都有对应的提示
        - 系统出错时的提示可以被普通用户理解
        - 系统出错时的提示可以为专业人员解决问题提供帮助
    + 用户进行非法操作时有对应的提示
    + 系统加载过程中有对应的提示

### 开发人员可维护性
1. 先决条件：上述功能测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统代码应便于开发人员维护
    + 代码的命名规范，采用驼峰命名方式
    + 代码有易于理解的注释
    + 代码有合理的排版
    + 代码没有大量的重复和冗余
    + 代码有合理的错误处理方法和异常抛出
    + 代码被分解为合适的模块

## 符合法律法规
### 符合国家安全标准
1. 先决条件：上述功能与质量测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
    - 系统安全性符合中华人民共和国国家标准GB/T 22239-2008。
    - 《信息系统安全等级保护基本要求》中每一项出题系统都符合。

### 符合网站信息服务标准
1. 先决条件：上述功能与质量测试项已经通过
2. 代码版本：CS_TESTMAKER_2.0
3. 测试项:
  - 系统运营符合《非经营性互联网信息服务备案管理办法》。
  - 做好已备案网站主页备案编号的悬挂和链接工作。


# 要测试的特性
## 特性与优先度
1. 优先度划分标准
\begin{tabular}{|p{2cm}|p{8cm}|}
\hline
优先度 & 说明\\
\hline
P1 & 核心功能测试用例，此部分测试用例如果失败会阻碍系统核心功能与大部分其他测试用例的验证\\
\hline
P2 & 高优先级测试用例，最常执行以保证功能性稳定；基本功能测试，和重要的错误、边界测试\\
\hline
P3 & 中优先级测试用例，更全面地验证功能的各个方面，异常测试，边界，中断等测试用例\\
\hline
P4 & 低优先级测试用例，不常常被执行，性能、压力、兼容性、稳定性、安全、可用性等等\\
\hline
\end{tabular}

2. 需测试特性与优先度
\begin{tabular}{|p{10cm}|}
\hline
P1\\
\hline
出题系统用户登录校验\\
\hline
主持人创建项目\\
\hline
主持人新建考题\\
\hline
主持人修改状态(开始-编写)\\
\hline
作者修改状态(编写-评审) \\
\hline
评审员设置评审结果为“可接受” \\
\hline
评审员设置评审结果为“被拒绝”\\
\hline
评审员设置评审结果为“需修改” \\
\hline
主持人修改状态(开始-编写)\\
\hline
评审员评审权限\\
\hline
质管员设置再审结果为“可发布” \\
\hline
质管员设置再审结果为“需修改” \\
\hline
质管员设置再审结果为“需作废”\\
\hline
质管员再审权限\\
\hline
作者修改考题\\
\hline
作者修改权限\\
\hline
主持人导出发布考题\\
\hline
主持人导入题库\\
\hline
有权限用户查阅考题\\
\hline
生成考卷\\
\hline
批改考题\\
\hline
在线报名考生管理系统用户登录校验\\
\hline
查看考卷与作答\\
\hline
\end{tabular}

\begin{tabular}{|p{10cm}|}
\hline
P2\\
\hline
主持人设置考题期限\\
\hline
作者设置多类型考题\\
\hline
主持人重启出题流程\\
\hline
\end{tabular}

\begin{tabular}{|p{10cm}|}
\hline
P3\\
\hline
送审前内容检查\\
\hline
主持人废除作废考题\\
\hline
\end{tabular}

\begin{tabular}{|p{10cm}|}
\hline
P4\\
\hline
用户修改个人信息\\
\hline
修改次数超过提醒\\
\hline
响应速度\\
\hline
浏览器可移植性\\
\hline
平台可移植性\\
\hline
数据库可移植性\\
\hline
用户安全性需求\\
\hline
系统一致性需求\\
\hline
数据安全性需求\\
\hline
系统安全性需求\\
\hline
数据可靠性\\
\hline
系统可靠性\\
\hline
用户易用性\\
\hline
系统易用性\\
\hline
开发人员可维护性\\
\hline
符合国家安全标准\\
\hline
\end{tabular}

## 测试特性风险评估
### 出题系统
#### 用户登录校验-P1
1. 用户以非法方式登入系统
    + 描述：用户利用SQL注入等方式，绕过登录校验以管理员等身份登陆进系统；可能造成恶意用户对系统数据的篡改和删除
    + 可能性：中
    + 影响程度：高
    + 缓解措施：加强对登录页面的输入校验，过滤恶意输入
    + 风险级别：高

2. 合法用户无法登入系统
    + 描述：因为数据库损坏等原因，合法用户无法正常登入系统
    + 可能性：低
    + 影响程度：中
    + 缓解措施：对数据进行备份
    + 风险级别：中

#### 用户修改个人信息-P4

1. 用户个人信息保存失败
    + 描述：因为网络连接失败或并发过高，用户修改个人信息后无法保存
    + 可能性：低
    + 影响程度：低
    + 缓解措施：对用户的信息在本地进行储存，重新请求
    + 风险级别：低

#### 主持人创建项目-P1

1. 主持人创建项目失败
    + 描述：由于网络错误等原因，主持人创建项目时无法成功对项目进行规划，如限制项目考题数量或考题范围，或创建项目成功后无法保存设置
    + 可能性：低
    + 影响程度：中
    + 缓解措施：合理设置主持人的权限并用log记录其行动，方便进行行动复现
    + 风险级别：高

#### 主持人新建考题-P1

1. 主持人新建考题失败
    + 描述：由于网络错误等原因，主持人无法设置新考题的状态，属性或相关管理人员
    + 可能性：低
    + 影响程度：中
    + 缓解措施：合理设置主持人的权限并用log记录其行动，方便进行行动复现
    + 风险级别：高

2. 系统发送邮件失败
    + 描述：系统没有成功将邮件发送给相关管理人员
    + 可能性：中
    + 影响程度：中
    + 缓解措施：若相关管理人员一段时间内没有登入系统则重发邮件
    + 风险级别：中

#### 主持人设置考题期限-P2

1. 主持人设置考题期限失败
    + 描述：主持人无法设定考题状态或错误设定评审考题的时间限期
    + 可能性：中
    + 影响程度：中
    + 缓解措施：合理设置主持人的权限并用log记录其行动，方便进行行动复现；对主持人输入的时间限期是否合理进行检查
    + 风险级别：高

#### 主持人修改状态(开始-编写)-P1

1. 主持人修改状态失败
    + 描述：主持人对于未完成设置的题目修改了状态，或完成设置后无法修改状态
    + 可能性：低
    + 影响程度：中
    + 缓解措施：为防止高并发情况下出现此种状况，修改状态时对题目的设置进行检查，合理设置主持人的权限
    + 风险级别：高

2. 系统发送邮件失败
    + 描述：系统没有成功将邮件发送给相关管理人员
    + 可能性：中
    + 影响程度：中
    + 缓解措施：若相关管理人员一段时间内没有登入系统则重发邮件
    + 风险级别：中 

#### 作者设置多类型考题-P2

1. 作者无法编写带有表格，图形等的考题
    + 描述：由于富文本编辑器的bug，作者无法在考题中插入表格及图形或表格或图形出现乱码
    + 可能性：中
    + 影响程度：中
    + 缓解措施：在上线前对文本编辑器进行多轮测试并提供备用编辑器
    + 风险级别：中

2. 作者导入考题时利用不合法文件进行攻击
    + 描述：作者在XML中插入后门，在系统解析XML时对系统进行攻击
    + 可能性：低
    + 影响程度：高
    + 缓解措施：对用户上传的XML文件进行过滤
    + 风险级别：中

#### 作者修改状态(编写-评审)-P1

1. 作者错误修改状态
    + 描述：作者对未完成编写的题目修改了状态或作者编写完成后无法修改题目状态
    + 可能性：低
    + 影响程度：中
    + 缓解措施：为防止高并发前提下出现此种状态，在修改状态的请求前对题目的编写状态进行确认
    + 风险级别：高

#### 评审前内容检查-P3

1. 评审前没有完全审核应审的项目就使状态修改成功
    + 描述：作者勾选了相应的题目附件却没有上传就选择了改变状态
    + 可能性：高
    + 影响程度：低
    + 缓解措施：在之后的评审阶段进行打回
    + 风险级别：低

#### 评审员设置评审结果（可接受/被拒绝/需修改）-P1

1. 系统发送邮件失败
    + 描述：系统没有成功将邮件发送给相关管理人员
    + 可能性：中
    + 影响程度：中
    + 缓解措施：若相关管理人员一段时间内没有登入系统则重发邮件
    + 风险级别：中

#### 评审员评审权限-P1
1. 评审员权限错误
    + 描述：因为权限设置失败，评审员无法阅读及编辑属于自己评审的考题或有权阅读及编辑不属于自己评审的考题
    + 可能性：低
    + 影响程度：高
    + 缓解措施：上线前进行多种权限测试；在考题处设置申请访问权限的入口，在检测到越权的修改记录后对评审员账户进行封禁
    + 风险级别：高

#### 质管员设置再审结果（可发布/需修改/需作废）-P1

1. 系统发送邮件失败
    + 描述：系统没有成功将邮件发送给相关管理人员
    + 可能性：中
    + 影响程度：中
    + 缓解措施：若相关管理人员一段时间内没有登入系统则重发邮件
    + 风险级别：中

#### 质管员再审权限-P1

1. 质管员再审权限错误
    + 描述：因为权限设置失败，质管员无法阅读及编辑属于自己再审的考题或有权阅读及编辑不属于自己再审的考题
    + 可能性：低
    + 影响程度：高
    + 缓解措施：上线前进行多种权限测试；在考题处设置申请访问权限的入口，在检测到越权的修改记录后对质管员账户进行封禁
    + 风险级别：高

#### 作者修改考题-P1

1. 系统发送邮件失败
    + 描述：系统没有成功将邮件发送给相关管理人员
    + 可能性：中
    + 影响程度：中
    + 缓解措施：若相关管理人员一段时间内没有登入系统则重发邮件
    + 风险级别：中

#### 作者修改权限-P1
1. 作者修改权限未落实
    + 描述：因为权限设置失败，作者无法阅读及编辑需要自己修改的考题或有权阅读及编辑不属于自己修改的考题
    + 可能性：低
    + 影响程度：高
    + 缓解措施：上线前进行多种权限测试；在考题处设置申请访问权限的入口，在检测到越权的修改记录后对作者账户进行封禁
    + 风险级别：高
    
#### 修改次数超过提醒-P4
1. 系统在某考题修改次数超过3次时没有提醒主持人
    + 描述：在修改次数大于3次时没有提醒主持人
    + 可能性：低
    + 影响程度：低
    + 缓解措施：支持人自己按时查看出题系统内题目状态
    + 风险级别：低

#### 主持人导出发布考题-P1

1. 发布考题数据损坏
    + 描述：因为数据损坏，考题无法被阅读，主持人无法导出考题或导出的考题中含有冗余数据
    + 可能性：低
    + 影响程度：高
    + 缓解措施：对数据进行备份
    + 风险级别：高

2. 导出的考题不符合考题导出规则
    + 描述：因为在考题导出过程中规则被修改等情况，考题不符合考题导出规则
    + 可能性：低
    + 影响程度：中
    + 缓解措施：导出考题前重新对规则进行检查
    + 风险级别：高

#### 主持人导入题库-P1

1. 管理员导入考题时利用不合法文件进行攻击
    + 描述：管理员导入考题时在XML中插入后门，在系统解析XML时对系统进行攻击
    + 可能性：低
    + 影响程度：高
    + 缓解措施：对输入文件进行格式检查和非法字符过滤
    + 风险级别：中

#### 主持人废除作废考题-P3

1. 废除后的考题仍能被使用
    + 描述：由于主持人的废除操作被打断等原因，废除后的考题仍然能被查看及使用
    + 可能性：低
    + 影响程度：中
    + 缓解措施：对主持人的操作进行log记录以方便重现
    + 风险级别：低

#### 主持人重启出题流程-P2

1. 旧项目中的考题仍能被阅读或修改
    + 描述：由于主持人的重启操作被打断等原因，旧项目中的考题仍能被阅读或修改
    + 可能性：低
    + 影响程度：低
    + 缓解措施：每次项目被使用时对项目状态进行确认
    + 风险级别：低

2. 新项目中的考题无法正常使用
    + 描述：由于主持人的重启操作被打断等原因，新项目中的考题无法正常使用
    + 可能性：低
    + 影响程度：高
    + 缓解措施：检测到考题无法正常使用时对新建项目中的考题进行备份，以便再次新建时可以被使用
    + 风险级别：高

### 题库管理系统
#### 有权限用户查阅考题-P1
1. 无权限用户查阅到了考题
    + 描述：无权限用户也能看见考题和答案
    + 可能性：低
    + 影响程度：高
    + 缓解措施：限制可登陆题库管理系统的账户
    + 风险级别：高

#### 生成考卷-P1
1. 考卷未能按照规则生成
    + 描述：考卷没有按照考卷组成规则自动生成
    + 可能性：高
    + 影响程度：高
    + 缓解措施：加入生成后的人工检查
    + 风险级别：高

2. 考卷生成后答案未能成功生成
    + 描述：考卷生成时答案导出错误或者没有导出答案
    + 可能性：高
    + 影响程度：高
    + 缓解措施：加入生成后的人工检查
    + 风险级别：高

### 考试系统
#### 批改考题-P1
1. 错误批改考题
    + 描述：系统没有按照标准答案成功批改考题
    + 可能性：高
    + 影响程度：高
    + 缓解措施：加入人工检查
    + 风险级别：高

### 在线报名考生管理系统
#### 用户登录校验-P1
1. 用户以非法方式登入系统
    + 描述：用户利用SQL注入等方式，绕过登录校验以他人身份登陆进系统；可能造成恶意用户对他人考卷随意作答及他人成绩信息泄露
    + 可能性：中
    + 影响程度：高
    + 缓解措施：加强对登录页面的输入校验，过滤恶意输入
    + 风险级别：高

2. 合法用户无法登入系统
    + 描述：因为数据库损坏等原因，合法用户无法正常登入系统
    + 可能性：低
    + 影响程度：中
    + 缓解措施：对数据进行备份
    + 风险级别：高

#### 查看考卷与作答-P1
1. 用户无法查看将要作答的考卷
    + 描述：因系统错误考卷不能显示 
    + 可能性：低 
    + 影响程度：高
    + 缓解措施：人工干预
    + 风险级别：高

2. 用户作答后无法看见自己成绩
    + 描述：因系统错误考卷分数不能显示 
    + 可能性：低 
    + 影响程度：中
    + 缓解措施：通过老师，主持人角色查看并告知
    + 风险级别：中

### 系统质量
#### 响应速度-P4
1. 用户使用系统时卡顿
    + 描述：用户在进行操作时网页响应速度很慢
    + 可能性：中 
    + 影响程度：中
    + 缓解措施：提高网速，在系统负荷不大的时候工作
    + 风险级别：高

#### 浏览器可移植性-P4
1. 不可移植
    + 描述：某些主流浏览器不支持网页的正确显示
    + 可能性：高 
    + 影响程度：中
    + 缓解措施：更换至支持的浏览器上使用
    + 风险级别：高
    
#### 平台可移植性-P4
1. 不可移植
    + 描述：如系统只能在windows系统上运行，mac系统不支持
    + 可能性：高 
    + 影响程度：中
    + 缓解措施：更换至有可以运行系统的电脑环境下使用
    + 风险级别：高

#### 用户安全性需求-P4
1. 用户可以越权
    + 描述：用户越权访问到自己本看不到的内容，比如学生看见考题与答案
    + 可能性：中 
    + 影响程度：高
    + 缓解措施：严格规范系统防止越权
    + 风险级别：高

#### 系统一致性需求-P4
1. 系统不一致
    + 描述：系统在突然断电情况下数据丢失
    + 可能性：高 
    + 影响程度：高
    + 缓解措施：做好数据库事务日志记录
    + 风险级别：高

#### 数据安全性需求-P4
1. 数据未加密
    + 描述：恶意用户劫持了网站的传输并看见了传输中的未加密考卷与答案
    + 可能性：中
    + 影响程度：高
    + 缓解措施：出题系统至题库管理系统至考试系统中考卷和答案的传输在离线情况或完全可靠状态下进行
    + 风险级别：高
    
#### 系统安全性需求-P4
1. 系统遭受攻击
    + 描述：系统容易被攻击导致无法正常提供服务 
    + 可能性：中
    + 影响程度：高
    + 缓解措施：人工干预，发现攻击时及时将攻击者ip列入黑名单
    + 风险级别：高

#### 数据可靠性-P4
1. 数据不可靠
    + 描述：已变更的数据因为系统异常退出，更新没有保存至数据库 
    + 可能性：中
    + 影响程度：高
    + 缓解措施：做好事务日志记录与回滚
    + 风险级别：高

#### 系统可靠性-P4
1. 系统不可靠
    + 描述：软件系统会经常错误退出，闪退
    + 可能性：中
    + 影响程度：高
    + 缓解措施：人工干预
    + 风险级别：高

#### 用户易用性-P4
1. 界面复杂
    + 描述：用户难以快速上手系统使用
    + 可能性：低 
    + 影响程度：低
    + 缓解措施：配置使用文档
    + 风险级别：低
    
#### 系统易用性-P4
1. 系统缺少操作成功的提示
    + 描述：在操作成功时没有提示
    + 可能性：中
    + 影响程度：低
    + 缓解措施：用户可以通过界面变更判断是否成功
    + 风险级别：低
2. 系统缺少操作失败的提示
    + 描述：在操作失败时没有提示，用户不知道失败原因
    + 可能性：中
    + 影响程度：中
    + 缓解措施：用户可以通过界面变更判断是否成功，失败则再来一次
    + 风险级别：中

#### 开发人员可维护性-P4
1. 代码规范度差
    + 描述：项目代码没有规范
    + 可能性：中
    + 影响程度：中
    + 缓解措施：与开发人员直接沟通
    + 风险级别：中

### 法律法规
#### 符合国家安全标准-P4
1. 系统有不符合中华人民共和国国家标准GB/T 22239-2008的部分
    + 可能性：低
    + 影响程度：高 
    + 缓解措施：与开发人员直接沟通改正
    + 风险级别：高
  
## 测试用例规范：
- 用例类型：功能测试、性能测试、配置相关、安装部署、安全相关、接口测试、其他
- 适用阶段：单元测试阶段、功能测试阶段、集成测试阶段、系统测试阶段、冒烟- 测试阶段、版本验证阶段
- 相关需求：测试用例关联的需求名称
- 用例标题：相关需求名-用例概括-编号
- 优先级：1、2、3、4
- 前置条件：用例测试的前置条件描述
- 用例步骤与预期结果
- 关键词


# 不会被测试的特性
## 并发要求
- 描述：支持动态用户（在线用户）在1500 以上，支持静态用户（注册用户）
在50000 以上，支持并发数（同时工作用户）300 以上。
- 原因：暂无资源同时测试要求数量的用户同时在线的情景
- 风险评估：按照实际情况认为出题子系统，题库管理系统在使用中 不需要很高的并发度，而在线报名考生管理系统和考生系统对并发度有一定的要求，但可以在实际使用中通过人为规定，时间分流等方式避免。判定风险级别为：一般损失。

## 数据库可移植性
- 描述：出题系统的数据库有很好的更新能力，能够适应迭代开发。替换关系数据库系统的平均时间不超过2 小时，并且保证没有数据丢失。便于之后出现系统升级更换数据
库系统的情况。
- 原因：暂无大规模的考题数据和用户数据内容资源，暂无多个数据库系统可供测试
-风险评估：根据实际情况判定，在线出题考试系统的数据增长有上限，数据库移植的可能性也较低。判定风险级别为：一般损失。

## 符合网站信息服务标准 
- 描述：做好已备案网站主页备案编号的悬挂和链接工作。
- 原因：暂无已备案域名与服务器资源，测试暂只针对离线网页版的在线出题考试系统，无需进行链接是否合法的测试。判定风险级别为：没有损失。


# 方法
## 流程功能方面的特征
### 测试技术
+ 合法操作希望得到预期的结果
+ 非法的操作希望显示错误信息/提示

### 测试方法
采用决策表法和流程分析法,测试与流程有关的测试用例
作为补充,采用探索测试加强测试

### 测试工具
自动测试工具

### 开始/完成标准
+ 开始: 用例设计完成,人员分配完成,资源准备完成.
+ 完成: 测试用例全部执行完毕,结果预期或可控

### 测试所需时间
与测试特征相关,范围在2~10人时

### 测试约束
+ 测试项: 可得
+ 测试资源: 可得

### 相应测试特征
+ 主持人创建项目
+ 主持人新建考题
+ 主持人设置考题期限
+ 主持人修改状态(开始-编写)
+ 作者设置多类型考题
+ 作者修改状态(编写-评审)
+ 送审前内容检查
+ 评审员设置评审结果为“可接受”
+ 评审员设置评审结果为“被拒绝”
+ 评审员设置评审结果为“需修改”
+ 质管员设置再审结果为“可发布”
+ 质管员设置再审结果为“需修改”
+ 质管员设置再审结果为“需作废”
+ 作者修改考题
+ 修改次数超过提醒
+ 主持人导出发布考题
+ 主持人导入题库
+ 主持人废除作废考题
+ 主持人重启出题流程
+ 查看考卷与作答
+ 生成考卷
+ 批改考题

## 与权限有关的测试方法
### 测试技术
+ 合法操作希望得到预期的结果
+ 非法的操作希望显示错误信息/提示

### 测试方法
采用状态转换法,测试与权限有关的测试用例.
作为补充,采用探索测试加强测试.

### 测试工具
自动测试工具

### 开始/完成标准
+ 开始: 用例设计完成,人员分配完成,资源准备完成.
+ 完成: 测试用例全部执行完毕,结果预期或可控

### 测试所需时间
与测试特征相关,范围在2~6人时

### 测试约束
+ 测试项: 可得
+ 测试资源: 可得

### 相应测试特征
+ 质管员再审权限
+ 有权限用户查阅考题
+ 评审员评审权限
+ 作者修改权限

## 用户管理测试方法
### 测试技术
+ 合法操作希望得到预期的结果
+ 非法的操作希望显示错误信息/提示

### 测试方法
采用等价类/边界值方法,测试与用户账户管理的测试用例.
作为补充,采用探索测试加强测试.

### 测试工具
自动测试工具

### 开始/完成标准
+ 开始: 用例设计完成,人员分配完成,资源准备完成.
+ 完成: 测试用例全部执行完毕,结果预期或可控

### 测试所需时间
3人时

### 测试约束
+ 测试项: 可得
+ 测试资源: 可得

### 相应测试特征
+ 用户登录校验
+ 用户修改个人信息

## 质量等相关的特征测试方法
### 测试技术
+ 合法操作希望得到预期的结果
+ 非法的操作希望显示错误信息/提示

### 测试方法
暂定,平台相关的特性可以使用兼容性测试

### 测试工具
自动测试工具

### 开始/完成标准
+ 开始: 用例设计完成,人员分配完成,资源准备完成.
+ 完成: 测试用例全部执行完毕,结果预期或可控

### 测试所需时间
与特征相关,范围在4~12人时

### 测试约束
+ 测试项: 可得
+ 测试资源: 可得

### 相应测试特征
+ 响应速度
+ 浏览器可移植性
+ 平台可移植性
+ 用户安全性需求
+ 系统一致性需求
+ 数据安全性需求
+ 系统安全性需求
+ 数据可靠性
+ 系统可靠性
+ 用户易用性
+ 系统易用性
+ 开发人员可维护性
+ 符合国家安全标准


# 测试项通过/失败准则
1. 组件测试相关准则
    + 通过准则
        - 关于该组件接口的准则通过率达100%
        - 代码覆盖率达80%以上
    + 失败准则
        - 任意测试组件的相关准则有不符合的条目即为失败
2. 集成测试相关准则
    + 通过准则
        - 所有接口测试通过率达100%
        - 单元测试平均代码覆盖率达80%以上
3. 系统测试相关准则
    + 通过准则
        - 该版本的系统功能能够完整运作
4. 验收测试相关准则
    + 通过准则
        - 软件需求分析说明书中定义的所有功能已全部实现，性能指标全部达到要求。
        - 所有测试项没有残余的一级二级三级四级的错误。
        - 立项审批表、需求分析文档、设计文档和编码实现一致。
        - 验收测试工件齐全（测试计划，测试用例，测试日志，测试通知单，测试分析报告）

# 暂停准则和继续准则
- 暂停准则列表
    + 当系统环境中必要的jar依赖包受到损坏或丢失，以至于系统无法启动时，测试暂停
    + 某组件相关测试准则通过率小于50%时测试暂停
- 继续准则列表
    + 因测试项准则通过率过低而被暂停的测试，开发人员修复结束后继续进行
    + 系统能够启动（主页能够在浏览器上被正常显示）时，测试继续
    + 测试暂停时进行到一半的测试活动需要被重启
    
# 测试交付物
- 完整测试计划
- 测试设计规范
- 测试用例规范
- 测试程序规范
- 测试项目传送报告
- 测试日志
- 测试事故报告
- 测试总结报告
- 测试数据
- 测试工具记录

# 测试任务
## 准备测试任务
### 测试计划编写
+ 交付物：测试计划
+ 相关依赖：详细的需求说明及用户文档
+ 内容：对测试过程的整体规划，将成为后续任务的依赖

## 执行测试任务
### 白盒测试
+ 交付物：白盒测试报告
+ 相关依赖：项目源代码及单元测试工具等
+ 内容：通过检查软件内部的逻辑结构，对软件中的逻辑路径进行覆盖测试。在程序不同地方设立检查点，检查程序的状态，以确定实际运行状态与预期状态是否一致

### 黑盒测试
+ 交付物：黑盒测试报告
+ 相关依赖：可用的各功能接口
+ 内容：在完全不考虑程序内部结构和内部特性的情况下，在程序接口进行测试，检查程序功能是否按照需求规格说明书的规定正常使用，程序是否能适当地接收输入数据而产生正确的输出信息

### 性能测试
+ 交付物：性能测试报告
+ 相关依赖：QALoad、LoadRunner、Benchmark Factory和Webstress等性能测试工具
+ 内容：通过自动化的测试工具模拟多种正常、峰值以及异常负载条件来对系统的各项性能指标进行测试

### 安全性测试
+ 交付物：安全测试报告
+ 相关依赖：国家安全标准参考
+ 内容：验证安装在系统内的保护机制能否在实际应用中对系统进行保护，使之不被非法入侵，不受各种因素的干扰

### 静态测试
+ 交付物：静态测试报告
+ 相关依赖：项目源代码，代码书写规范，各阶段文档
+ 内容：通过分析或检查源程序的语法、结构、过程、接口等来检查程序的正确性。对需求规格说明书、软件设计说明书、源程序做结构分析、流程图分析、符号执行来寻找漏洞

### 场景测试
+ 交付物：场景测试报告
+ 相关依赖：能够顺利工作的完整系统
+ 内容：模拟特定场景边界发生的事情，通过事件来触发某个动作的发生，观察事件的最终结果，从而用来发现需求中存在的问题


# 环境需求
+ 硬件环境
    - 能够连到互联网的个人电脑（若为Windows则需Windows7以上系统，内存大于等于2G）
    - 方便的实时语音通讯工具
+ 软件环境
    - Java 1.8 运行环境
    - Maven
    - 适当的Java IDE
+ 测试数据
    - 用户数据包含多位主持人、作者、评审员、质管员，具体数据来源复旦大学软件学院教师资料
+ 工具
    - https://codecov.io
    - https://jenkins.io
    - https://semmle.com/codeql
    - https://travis-ci.org
    - https://www.appveyor.com
    
# 责任
- 出题系统、考试系统测试小组：
    + Chen Wang：管理与出题系统和考试系统功能相关的所有测试、检查测试用例设计是否符合规范、总结测试结果
    + Jiaxing Liu：为小组负责的测试项设计测试用例、作证测试用例执行结果
    + Chenning Wu：执行测试用例并记录
- 题库管理系统、在线报名考生管理系统测试小组：
    + Yihan Zhang：管理与题库管理系统和在线报名考生管理系统功能相关的所有测试、检查测试用例设计是否符合规范、总结测试结果
    + Cenyuan Zhang：为小组负责的测试项设计测试用例、作证测试用例执行结果
    + Ruixin Shi：执行测试用例并记录
- 集成测试小组：
    + Jia'ni Huang：管理与系统非功能需求相关的所有测试及子系统之间的接口测试、检查测试用例设计是否符合规范、总结测试结果
    + Jiahe Tian：为小组负责的测试项设计测试用例、作证测试用例执行结果
    + Xiaoxiao Hu：执行测试用例并记录
- 提供测试项的小组：Ruixin Shi、Xiaoxiao Hu、Jiahe Tian
- 提供环境需求的小组：Chen Wang、Jiaxing Liu、Cenyuan Zhang

# 人手和培训的需要
- 测试工具培训
    + 培训师：Chen Wang
    + 资质：参与多次大型项目开发与测试工作，熟悉当今流行的测试工具
- 测试流程规范培训
    + 培训师：Jiaxing Liu
    + 资质：上市公司合作人，具有丰富的管理经验，可以轻松协调安排组内成员测试的规范性和一致性
    
\begin{tabular}{|p{2cm}|p{3.3cm}|p{8cm}|}
\hline
测试人员 & 需求技能 & 需求培训\\
\hline
Chen Wang & 熟悉测试工具、文档规范 & 测试流程规范培训\\
\hline
Jiaxing Liu & 熟悉测试用例设计规范 & 测试工具培训\\
\hline
Chenning Wu & 熟悉文档规范、程序代码、测试工具 & 测试流程规范培训、测试工具培训\\
\hline
Yihan Zhang & 熟悉测试工具、文档规范 & 测试流程规范培训、测试工具培训\\
\hline
Cenyuan Zhang & 熟悉测试用例设计规范 & 测试流程规范培训、测试工具培训\\
\hline
Ruixin Shi & 熟悉文档规范、程序代码、测试工具 & 测试流程规范培训、测试工具培训\\
\hline
Jia'ni Huang & 熟悉测试工具、文档规范 & 测试流程规范培训、测试工具培训\\
\hline
Jiahe Tian & 熟悉测试用例设计规范 & 测试流程规范培训、测试工具培训\\
\hline
Xiaoxiao Hu & 熟悉文档规范、程序代码、测试工具 & 测试流程规范培训、测试工具培训\\
\hline
\end{tabular}

# 时间表

## 总体时间表

\begin{tabular}{|p{1.8cm}|p{3.3cm}|p{8cm}|}
\hline
3月24日-4月5日 & 测试计划的编撰 & -\\
\hline
4月6日-4月20日 & 白盒测试用例设计与执行 & 4月6日-4月10日：小组讨论及用例编写\newline4月11日-4月18日：具体执行及结果记录\newline4月19日-4月20日：总结及报告撰写\\
\hline
4月21日-5月11日 & 黑盒测试用例设计与执行 & 4月21日-4月26日：小组讨论及用例编写\newline4月27日-5月9日：具体执行及结果记录\newline5月10日-5月11日：总结及报告撰写\\
\hline
5月12日-5月18日 & 性能测试用例设计与执行 & 5月12日-5月13日：小组讨论及用例编写\newline5月14日-5月16日：具体执行及结果记录\newline5月17日-5月18日：总结及报告撰写\\
\hline
5月19日-5月25日 & 安全性测试与静态测试用例设计与执行 & 5月19日-5月20日：小组讨论及用例编写\newline5月21日-5月23日：具体执行及结果记录\newline5月24日-5月25日：总结及报告撰写\\
\hline
5月26日-6月1日 & 场景测试用例设计与执行 & 5月26日-5月27日：小组讨论及用例编写\newline5月28日-5月30日：具体执行及结果记录\newline5月31日-6月1日：总结及报告撰写\\
\hline
\end{tabular}

## 里程碑

+ 需求冻结：需求完全确定且不再进行版本更新
+ 计划完成：测试计划书定稿
+ 白盒测试完成：所有测试用例通过率达到100%，代码覆盖率达80%以上
+ 黑盒测试完成：所有测试用例通过率达到100%
+ 安全性测试完成：所有测试用例通过率达到100%
+ 静态测试完成：代码全部审核完成且更改完毕
+ 场景测试完成：所有测试用例通过率达到100%
+ 项目发布

# 风险以及应急措施
## 项目风险评估
### 评估方式简述
对项目进行了结构化风险评估、技术风险评估和规模风险评估，每一项评估项给出L-低级，M-中级，H-高级的评估结果，并根据每一项的重要程度决定其L/M/H的级别分数（例如现存系统变化频率的NA=0，L=1，M=1，H=3；与该项目相关的业务领域的变化程度的L=1，M=2，H=4）。同时给出每一个风险评估项的权值，最后得出风险值=级别x权值。\newline
下面给出本项目在每一个风险评估项的打分结果。

### 结构化风险评估
1. 现存系统的变化频率
    + 级别: (M=2)-每年2到10次
    + 权值: 3
    + 分值: 6

2.  与该项目相关的业务领域的变化程度
    + 级别: (L=1)-很少的变化
    + 权值: 3
    + 分值: 3

3. 项目的组织类型
    + 级别: (L=1)-对员工进行总体管理控制
    + 权值: 2
    + 分值: 2

4. 正在进行的项目培训状况
    + 级别: (L=1)-适当的完成培训计划
    + 权值: 2
    + 分值: 2

5. 项目组人员的技能水平
    + 级别: (M=2)-掌握主要组件的知识
    + 权值: 3
    + 分值: 6

6. 现存系统的辅助参考资料和/或相关文档以及其他信息的可利用性
    + 级别: (L=1)-容易利用
    + 权值: 3
    + 分值: 2

7. 用户文档状况
    + 级别: (L=1)-完整并且是最新的
    + 权值: 3
    + 分值: 3


*结构化风险评估总分为24,总权值为19,风险平均值为1.26*

### 技术风险评估
1. 在硬件或软件出错时完成任务的能力
    + 级别: (M=2)-在没有完整的操作系统时也能完成,但是有较少的能力要求
    + 权值: 2
    + 分值: 4

2. 系统的使用频率
    + 级别: (M=2)-每日使用(但不是每天24小时)
    + 权值: 2
    + 分值: 4

3. 依赖于和外部系统传送数据来完成功能的程度
    + 级别: (M=2)-必须从另一系统接受或传送数据
    + 权值: 2
    + 分值: 4

4. 对输入数据控制的程度
    + 级别: (M=2)-多功能,但是功能之间有联系
    + 权值: 2
    + 分值: 4

5. 系统复杂度
    + 级别: (M=2)-每日使用(但不是每天24小时)
    + 权值: 2
    + 分值: 4

6. 编程语言的特点
    + 级别: (L=1)-高级语言,使用广泛
    + 权值: 2
    + 分值: 2

7. 编程语言用于应用程序的适合程度
    + 级别: (L=1)-所有模块都可以用该语言编写,方法简单
    + 权值: 2
    + 分值: 2

8. 新技术、难技术、未验证的技术
    + 级别: (L=1)-没有没试验过的系统组件,没有领先的系统对象或技术
    + 权值: 5
    + 分值: 5

9. 项目小组对软件操作的熟悉程度
    + 级别: (L=1)-经验丰富
    + 权值: 2
    + 分值: 2

10. 错误的余地(需要完美的功能、处理时间极短和强大的合作协调能力)
    + 级别: (M=2)-现实的要求
    + 权值: 5
    + 分值: 10

11. 项目小组对系统运行环境的熟悉程度
    + 级别: (M=2)-有一些经验
    + 权值: 2
    + 分值: 4

12. 项目组对业务领域的知识水平
    + 级别: (M=2)-概念上的理解
    + 权值: 2
    + 分值: 4

13. 使用测试工具的类型
    + 级别: (L=1)-可以进行全面的软件测试,包括路径分析
    + 权值: 5
    + 分值: 5

14. 测试环境的真实性
    + 级别: (L=1)-测试是在可管理的测试环境上完成的
    + 权值: 4
    + 分值: 4

15. 软件适应变化的能力
    + 级别: (L=1)-高:使用结构编程技术、文档完备
    + 权值: 3
    + 分值: 3

*技术风险评估总分为61,总权值为42,风险平均值为1.45*

### 规模风险评估
1. 项目完成时间
    + 级别: (L=1)-12个月或更少
    + 权值: 3
    + 分值: 3

2. 项目进展与进度安排
    + 级别: (M=2)-符合进度表
    + 权值: 1
    + 分值: 2

3. 在系统内部相互联系的子系统
    + 级别: (M=2)-3~5个
    + 权值: 3
    + 分值: 6

4. 进行系统测试的项目资源的百分比
    + 级别: (M=2)-20%~40%
    + 权值: 2
    + 分值: 4

5. 关联的数据库
    + 级别: (L=1)-少于4个
    + 权值: 1
    + 分值: 1

6. 对项目的维护代码行数占整个系统开发代码行数的比例
    + 级别: (L=1)-低于开发代码行数的三分之一
    + 权值: 1
    + 分值: 1

*规模风险评估总分为17,总权值为11,风险平均值为1.55*

## 高分险假设及应急措施
由风险评估的结果,我们将高于模块平均值的风险认定为高风险.

### 结构化风险方面
+ 风险假设: 系统变化频率过高(如需求经常变更)、项目组人员技术水平较低(需要培训)
+ 应急措施: 项目组邀请专业人员指导、项目组加大技术人员参与

### 技术风险方面
+ 风险假设: 系统对外部有一定的依赖性、项目组人员对项目的理解可能之间存在偏差
+ 应急措施: 需求工程师需要详细地整理项目需求,技术人员尽量降低系统对外部的依赖或换用可靠性较高的外部

### 规模风险方面
+ 风险假设: 项目时间不足、系统本身复杂性带来一定的开发难度、项目资源不足
+ 应急措施: 与客户协商,加大资金投入,扩大项目规模,技术人员加班完成

# 授权
- 核准计划负责人：沈立炜（总监）
- 签名：
- 日期：

\pagebreak

# 参考文献 {-}
